import React from 'react';

const Slider = () => {

    return (
        <div>
            Slider is Here

            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet eum debitis voluptatem qui, laudantium accusantium quaerat provident est velit odit error atque. Molestiae nihil earum architecto reiciendis necessitatibus, dolorem minus? Totam voluptatum nesciunt fuga sed minima ea, sint corporis architecto eaque reprehenderit a tenetur soluta. Ex accusamus saepe, temporibus magnam dolore esse quibusdam non cupiditate doloremque molestiae eos delectus obcaecati sit consectetur eligendi reiciendis ratione ad vitae! Quis laboriosam accusantium, quidem enim veniam atque quam fugit soluta, eius dicta ex ipsa ducimus. Esse, sed facilis. Laudantium cupiditate vero nam veniam minus labore dolores fugiat laboriosam aliquid, quisquam sunt harum nobis expedita culpa inventore reiciendis ea nemo ipsam quaerat eum! Dolorum alias laborum, labore impedit eaque ipsa architecto ducimus dolor quo possimus iste aliquid nam. Obcaecati consequuntur veniam maxime beatae tenetur assumenda, cupiditate fugiat quas exercitationem corrupti molestias magnam dignissimos velit sequi suscipit. Tempore facilis, neque doloremque et quidem laudantium repellat, natus ipsa accusantium reiciendis aperiam saepe exercitationem quasi amet repellendus. Possimus delectus asperiores, error quis nemo libero corrupti nesciunt adipisci temporibus autem ex harum mollitia magni sequi repellat vel ipsam quibusdam animi voluptas vero natus quaerat architecto! Culpa, ipsum asperiores assumenda harum recusandae ipsa similique! Dicta perferendis obcaecati dolorum saepe!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet eum debitis voluptatem qui, laudantium accusantium quaerat provident est velit odit error atque. Molestiae nihil earum architecto reiciendis necessitatibus, dolorem minus? Totam voluptatum nesciunt fuga sed minima ea, sint corporis architecto eaque reprehenderit a tenetur soluta. Ex accusamus saepe, temporibus magnam dolore esse quibusdam non cupiditate doloremque molestiae eos delectus obcaecati sit consectetur eligendi reiciendis ratione ad vitae! Quis laboriosam accusantium, quidem enim veniam atque quam fugit soluta, eius dicta ex ipsa ducimus. Esse, sed facilis. Laudantium cupiditate vero nam veniam minus labore dolores fugiat laboriosam aliquid, quisquam sunt harum nobis expedita culpa inventore reiciendis ea nemo ipsam quaerat eum! Dolorum alias laborum, labore impedit eaque ipsa architecto ducimus dolor quo possimus iste aliquid nam. Obcaecati consequuntur veniam maxime beatae tenetur assumenda, cupiditate fugiat quas exercitationem corrupti molestias magnam dignissimos velit sequi suscipit. Tempore facilis, neque doloremque et quidem laudantium repellat, natus ipsa accusantium reiciendis aperiam saepe exercitationem quasi amet repellendus. Possimus delectus asperiores, error quis nemo libero corrupti nesciunt adipisci temporibus autem ex harum mollitia magni sequi repellat vel ipsam quibusdam animi voluptas vero natus quaerat architecto! Culpa, ipsum asperiores assumenda harum recusandae ipsa similique! Dicta perferendis obcaecati dolorum saepe!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet eum debitis voluptatem qui, laudantium accusantium quaerat provident est velit odit error atque. Molestiae nihil earum architecto reiciendis necessitatibus, dolorem minus? Totam voluptatum nesciunt fuga sed minima ea, sint corporis architecto eaque reprehenderit a tenetur soluta. Ex accusamus saepe, temporibus magnam dolore esse quibusdam non cupiditate doloremque molestiae eos delectus obcaecati sit consectetur eligendi reiciendis ratione ad vitae! Quis laboriosam accusantium, quidem enim veniam atque quam fugit soluta, eius dicta ex ipsa ducimus. Esse, sed facilis. Laudantium cupiditate vero nam veniam minus labore dolores fugiat laboriosam aliquid, quisquam sunt harum nobis expedita culpa inventore reiciendis ea nemo ipsam quaerat eum! Dolorum alias laborum, labore impedit eaque ipsa architecto ducimus dolor quo possimus iste aliquid nam. Obcaecati consequuntur veniam maxime beatae tenetur assumenda, cupiditate fugiat quas exercitationem corrupti molestias magnam dignissimos velit sequi suscipit. Tempore facilis, neque doloremque et quidem laudantium repellat, natus ipsa accusantium reiciendis aperiam saepe exercitationem quasi amet repellendus. Possimus delectus asperiores, error quis nemo libero corrupti nesciunt adipisci temporibus autem ex harum mollitia magni sequi repellat vel ipsam quibusdam animi voluptas vero natus quaerat architecto! Culpa, ipsum asperiores assumenda harum recusandae ipsa similique! Dicta perferendis obcaecati dolorum saepe!
        </div>
    );
};

export default Slider;